sequence = input('Please introduce a DNA sequence')
sequence = sequence.lower()
length = len(sequence)
print('The total length is {}'.format(length))
a = sequence.count('a')
c = sequence.count('c')
g = sequence.count('g')
t = sequence.count('t')
print('A:', a)
print('C:', c)
print('G:', g)
print('T:', t)
